### DISCUSSION TITLE
How to set a default thumbnail in the media browser for media without artwork?

### DISCUSSION THREAD

**Discussion by richardwonka** [punxaphil/custom-sonos-card#112] [Q&A] [answered]
I have a few items in my media browser that do not have artwork and because of that, they differ in size and shape from the items with individual thumbnails:

![image](https://user-images.githubusercontent.com/304005/216384473-c68300b4-2ff0-478d-9906-1f7698c4f3ab.png)

I am hoping to be able to define a default thumbnail for those items in the media browser that do not have a thumbnail attached to them.

i have tried using `customthumbnailifmissing`, but with that I can only target _specific_ items by name. see this example, 
```
customThumbnailIfMissing: 
  "Soma FM: Cliqhop": https://cdn-icons-png.flaticon.com/512/651/651758.png
```
![image](https://user-images.githubusercontent.com/304005/216385282-3ef5362d-c131-4c9a-ad15-0fb3e3700812.png)

This defines a thumbnail for the item on the left, but _only_ for that.  I have not found a way to set a fallback.

any ideas on how I can define a fallback icon for missing artwork?

**Comment by punxaphil** [comment, marked as answer]
@richardwonka Can you try out this beta version of the card? [v5.20.0](https://github.com/johanfrick/custom-sonos-card/releases/tag/v5.20.0)
There is now a built in fallback if image is missing, and you can also override it.

**Reply by richardwonka** [reply]
thanks! yes, they are now evenly shaped and have a default image. 

I use a dark theme, so they're a bit glaring; how can I replace the image? or is there an alternative already for dark themes? 

edit: nevermind, I just read about `fallback` in the code :-)

also, adjacent topic:  the titles are now cut off - how can I get wrapped titles with a semi-transparent background over the thumbnail? - I use "#020202aa" for background of header and controls in the player section, but I don't know how to get full names in the media browser.

**Reply by richardwonka** [reply]
i have added the `fallback:` option (see code below), but am still seeing the built-in fallback. Might be a bug in the implementation? 
```
type: custom:sonos-media-browser
customThumbnailIfMissing:
  fallback: https://cdn-icons-png.flaticon.com/512/831/831337.png
layout:
  mobileThresholdPx: 500
  mediaItem:
    width: 33%
    mobileWidth: 50%
styles:
  button-section:
    border: none
    border-radius: 0.5em
  media-button:
    border: none
    border-radius: 0.5em
  media-button-title:
    background: '#020202aa'
```
