### DISCUSSION TITLE
How to Eliminate Scroll Bars in Media Player

### DISCUSSION THREAD

**Discussion by NR3Y** [punxaphil/custom-sonos-card#158] [Q&A] [answered]
Can somebody give me a hint how to force the media player card to be 100% high, which would hopefully get rid of the scroll bar. I've played around with _heightPercentage_ with values ranging from 75 to 110%, but that doesn't solve the problem. Below is a screenshot of what I'm seeing on my iPad, web browser and in the (Mac-based) Home Assistant app. (Clearly, there is no issue with the media browser having scroll bars, as the entries in the Playlists can be numerous.)

Both cards are in a panel view and are under a **custom:layout-card**, with a layout_type of **custom:grid**, which has rows set to _auto_

```
type: custom:layout-card
layout_type: custom:grid
cards:
  - type: custom:sonos-card
```
and
```
layout:
  grid-template-columns: 12% 12% 12% 12% 12% 12% 12% 12%
  grid-template-rows: auto
  justify-items: stretch
  height: auto
  rtl: false
  padding: 5px
```

![Screenshot 2023-07-30 at 10 36 46 AM](https://github.com/johanfrick/custom-sonos-card/assets/1959018/6400d6ca-3509-436a-949b-933b9d7e99c5)
