### DISCUSSION TITLE
Add ARTWORK as individual section (separated from player)

### DISCUSSION THREAD

**Discussion by chrispazz** [punxaphil/custom-sonos-card#164] [Q&A] [answered]
Is it possibile to have a separate section so that we can give specific size for a card containing only the artwork?

Thank you
Chris

**Comment by punxaphil** [comment, marked as answer]
```yaml
type: horizontal-stack
cards:
  - type: custom:sonos-card
    sections:
      - player
    card_mod:
      style:
        sonos-player$: |
          sonos-player-controls,sonos-player-header {
            display: none;
          }
  - type: custom:sonos-card
    sections:
      - groups
```
<img width="1097" alt="image" src="https://github.com/johanfrick/custom-sonos-card/assets/26582898/332b7d36-8c2f-4cbc-a08c-5e798ed789d9">
