### DISCUSSION TITLE
Style favorite items (card_mod)

### DISCUSSION THREAD

**Discussion by frederik0312** [punxaphil/custom-sonos-card#252] [Q&A] [answered]
I would like a simple way to display spotify content within the card.

Right now i have to click favorites -> browse media -> spotify -> playlists -> my playlist of choice

i would love for my playlists to be integrated in the player with the spotify feature so my path would look like this:
favorites -> and then have the classic spotify playlists interface Cover art + name.

Is this already possible or it it something that could be added?

Thanks!

**Comment by punxaphil** [comment]
It's not possible I'm afraid, but what you can do is to go in to the Sonos app and add your Spotify playlists to "my Sonos", then they will show up directly under favourites in the card.

**Comment by frederik0312** [comment]
Thanks, ill do that. Do you know how i Can style it myself to be bigger and in a grid formation? With cardmod? I find it really dificult to find the right dom elements😌

**Comment by punxaphil** [comment]
Have you read the docs? 😄 
```yaml
type: custom:sonos-card
mediaBrowserItemsPerRow: 5
```

**Comment by frederik0312** [comment]
thanks! yes i have read it many times trying to figure it out :)  Guess I must have missed it

**Comment by frederik0312** [comment]
I would love to style the favorite section a bit, could you provide me with the cardmod path to the playlist img element? i have been trying for a few hours now, would mean alot if it is possible :)

**Comment by punxaphil** [comment, marked as answer]
```yaml
type: custom:sonos-card
mediaBrowserItemsPerRow: 4
mediaBrowserShowTitleForThumbnailIcons: true
card_mod:
  style:
    sonos-media-browser$ sonos-media-browser-icons$: |
      div {            
        border: 1px solid white;
        color: red !important;
      }  
```
<img width="427" alt="image" src="https://github.com/johanfrick/custom-sonos-card/assets/26582898/00605bbd-4b18-4ff2-83fc-e226f47a737a">

---
[![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de)](https://www.buymeacoffee.com/punxaphil)
