### DISCUSSION TITLE
Changing the font size of song title with card-mod

### DISCUSSION THREAD

**Discussion by zapccu** [punxaphil/custom-sonos-card#265] [Q&A] [answered]
Hi,

I like to change the font size of the currently played song. My current - non working - approach:

```
card_mod:
  style:
    sonos-player:
      $: |
        .song {
          font-size: 1.2em;
        }
```

Is it possible to change the attributes?

Another question: Is it possible to hide elements? I like to hide the shuffle button. Which selector is needed in card-mod to address the buttons?

**Comment by punxaphil** [comment, marked as answer]
You are quite close. Here is the solution:
```yaml
type: custom:sonos-card
card_mod:
  style:
    sonos-player$ sonos-player-header$: |
      .song {
        font-size: 1.2em; !important;
      }
    sonos-player$ sonos-player-controls$ sonos-ha-player$ more-info-content$ more-info-media_player$: |
      ha-icon-button:nth-child(1) {
        display: none;
      }

```
