### DISCUSSION TITLE
How to show only player and now playing text information?

### DISCUSSION THREAD

**Discussion by perfrankling** [punxaphil/custom-sonos-card#293] [Q&A] [answered]
It would be great to be able to show only the text at the top of the player card, ie the player/artist/song/album info, turning off the display of artwork, buttons and volume control.

**Comment by punxaphil** [comment, marked as answer]
That's not what this card is intended for, to just show information. However if you still want to do that, you need something like card mod. Example:
```yaml
type: custom:sonos-card
heightPercentage: auto
sections:
  - player
card_mod:
  style:
    sonos-player$: |
      .artwork {
        display: none;
      }
      .controls {
        display: none;
      }
```
