### DISCUSSION TITLE
Change Thumbnail Title background

### DISCUSSION THREAD

**Discussion by ogoncalves200874** [punxaphil/custom-sonos-card#306] [Q&A] [answered]
First of all, congratulations on the excellent work! The Card just keeps getting better!

I have two questions:

- How can I change the Thumbnail Title background?
- How do I get the image of the albums in the sonos library to appear in favorites? (Radio, spotify are ok)

![Captura](https://github.com/punxaphil/custom-sonos-card/assets/37480241/e3cd2409-13b9-4c08-9084-32b8a9a4eade)

**Comment by punxaphil** [comment, marked as answer]
1. Use https://github.com/thomasloven/lovelace-card-mod
```yaml
type: custom:sonos-card
card_mod:
  style:
    sonos-media-browser$ sonos-media-browser-icons$: |
      .title {
        background-color: blue !important;
      }
```

2. 
Some issue with http I am guessing. Try `replaceHttpWithHttpsForThumbnails: true`. Or change from internal to external home assistant URL in the app
