### DISCUSSION TITLE
hide the volume button and percentage

### DISCUSSION THREAD

**Discussion by KazadorFR** [punxaphil/custom-sonos-card#324] [Q&A] [answered]
**Is your feature request related to a problem? Please describe.**
the volume button awkwardly superimposes 2 displays at 100%. The volume button may seem offset when it is with other similar settings such as a light slider (see screen)

**Describe the solution you'd like**
to hide the volume button to put a personalized slider and synchronize it with the volume with automation

**Describe alternatives you've considered**
hide the "mute" icon, hide the volume percentage, and adjust the size of the volume bar

and a big thank you for this great addon

![image](https://github.com/punxaphil/custom-sonos-card/assets/42878970/10980a67-6003-4858-b901-dd5a1c4d31c2)

**Comment by punxaphil** [comment, marked as answer]
```yaml
type: custom:sonos-card
card_mod:
  style:
    sonos-player$ sonos-player-controls$ sonos-volume$: |
      ha-control-slider {
        height: 10px;
      }
      .volume-level, ha-icon-button {
        display:none !important;
      }
```
<img width="399" alt="image" src="https://github.com/punxaphil/custom-sonos-card/assets/26582898/beaa978b-de40-4c1a-91af-7f904337f293">
