### DISCUSSION TITLE
Hide "All favorites" in top of card

### DISCUSSION THREAD

**Discussion by wormiedk** [punxaphil/custom-sonos-card#364] [Q&A] [answered]
I use a card to select my favorites from Sonos. I would love to be able to hide the header (All Favorites)
<img width="331" alt="image" src="https://github.com/punxaphil/custom-sonos-card/assets/4417857/f324d494-06ce-44bc-ba72-afeb2e12431a">

The code for the card is:
```
type: custom:sonos-card
sections:
  - media browser
entityId: media_player.stue_sonos
widthPercentage: 100
showVolumeUpAndDownButtons: false
topFavorites:
  - P1
  - P3
  - P4 øst
  - P6 BEAT
  - P8 JAZZ
hideGroupCurrentTrack: false
hideBrowseMediaButton: true
mediaBrowserHideTitleForThumbnailIcons: true
mediaBrowserItemsPerRow: 5
heightPercentage: 70

```

**Comment by wormiedk** [comment]
I tried using card mod but am not sure how to find the correct tag:
```
card_mod:
  style:
    sonos-media-browser-header:
      display: none;
```

**Comment by punxaphil** [comment, marked as answer]
```yaml
type: custom:sonos-card
card_mod:
  style:
    sonos-media-browser$: |
      sonos-media-browser-header {
        display: none;
      }
```
---
PunxaPhil
[![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de)](https://www.buymeacoffee.com/punxaphil)
