### DISCUSSION TITLE
How to write in YAML to change layout to get media part at the right side of the player?

### DISCUSSION THREAD

**Discussion by haz-69** [punxaphil/custom-sonos-card#54] [Q&A] [answered]
First, thanx for nice custom card!
A real rookie question:
How to write in YAML to change layout to get media part at the right side of the player?
I try to get the layout on the width instead of the hight to avid nedd of scrolling on my wall tablet.

**Comment by punxaphil** [comment, marked as answer]
Under layout, set mediaBrowser (and optionally mediaItem) widths. Example:
```yaml
type: custom:custom-sonos-card
layout:
  groups:
    width: 20%
  players:
    width: 20%
  mediaBrowser:
    width: 60%
  mediaItem:
    width: 15%
```
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/26582898/158894929-b79b341a-019d-4858-a3b0-21ad8ef6760c.png">

**Reply by vegardhw** [reply]
How do I remove a section like Groups or Media completely from the view?

**Reply by punxaphil** [reply]
```
type: custom:custom-sonos-card
styles:
  media-browser:
    display: none
```
