### DISCUSSION TITLE
Volume slider not available

### DISCUSSION THREAD

**Discussion by modem158** [punxaphil/custom-sonos-card#86] [Q&A] [answered]
Hello,

Great work on this project.  I'm using it with a few speakers scattered around the house.

For the life of me I can't get the volume sliders to show up on the media players for the individual speakers.

I see a bar that seems like it would be a slider but there is no actual slider and no button to pull across.  I've tried all the settings but I'm not making any progress.

[https://imgur.com/a/ZogWm47](https://imgur.com/a/ZogWm47)

```
title: "Sonos2"
path: "sonos2"
type: panel
cards:
  - type: custom:custom-sonos-card
    # Optional settings:
    name: ''
    groupsTitle: ''
    groupingTitle: ''
    mediaTitle: ''
    headerImage: ''
    shuffleFavorites: false
    noMediaText: 'No media selected'
    allVolumesText: 'All volumes'
    entityNameRegexToReplace: 'SONOS ' # Regex pattern to replace parts of the entity names
    entityNameReplacement: ''
    layout:
      mobileThresholdPx: 500 # Default is 650
      groups:
        width: '20%' # Default 25%
        mobileWidth: '80%' # Default 100%
      players:
        width: '20%' # Default 25%
        mobileWidth: '80%' # Default 100%
      mediaBrowser:
        width: '20%' # Default 33%
        mobileWidth: '80%' # Default 100%
      mediaItem:
        width: '20%' # Default 33%
        mobileWidth: '25%' # Default 16%
    selectedPlayer: media_player.sonos_kitchen # Forces this player to be the selected one on loading the card (overrides url param etc)
    backgroundBehindButtonSections: true # default is false, which means no background behind the different button sections
    hideGroupCurrentTrack: false # default is false, which means song/track info for groups will be shown
    skipAdditionalPlayerSwitches: false # default is false, which means additional switches will be shown in player if available (such as crossfade button)
    disableDynamicVolumeSlider: false # default is false. See more in section further down.
    mediaBrowserTitlesToIgnore:
      - Local Media
    entities: # Entities are automatically discovered if you don't supply this setting
      - media_player.sonos_kitchen
      - media_player.sonos_living_room
      - media_player.sonos_master_bedroom
      - media_player.sonos_office_upstairs
```
