### ISSUE TITLE
V7.20 Still “Apply” button and none responding “scripts”

### ISSUE THREAD

**Issue by MNLFDF** [punxaphil/custom-sonos-card#314]
**Checklist:**
- [X] I updated to the latest version available
- [X ] I cleared the cache of my browser

**Release with the issue:**
HA 2024.3

**Last working release (if known):**
V7.01

**Browser and Operating System:**
Home Assistant app for iPad (v17.4) and iPhone (v17.4)

**Description of problem:**
Installed 7.20. First it installed 7.20.beta4 (while I selected the 7.20), then Hacs notified there was a updat for the Sonos card to 7.20. I installed that. (Hacs confirmed 7.20 is installed now).

Then tried to select the second option in my list “JOE NL”. (See picture ). Then the Sonos card get me “JOE Easy” the first one on the list and again “Apply”. I can’t select any other options, because the card doesn’t seems to react on that selection. I can still pause the stream and turn up the volume tho.

And when I go to the favorites page, I can switch to another radio station.

The code I use for the dashboard:

```
type: custom:sonos-card
sections:
  - player
  - volumes
  - groups
  - grouping
  - media browser
predefinedGroups:
  - name: Joe Easy
    media: Joe Easy
    entities:
      - player: media_player.tv
        volume: 3
      - player: media_player.homecinema
        volume: 3
      - player: media_player.erker
        volume: 4
      - player: media_player.tafel
        volume: 3
      - player: media_player.keuken
        volume: 10
  - name: Joe NL
    media: JOE Nederland
    entities:
      - player: media_player.tv
        volume: 3
      - player: media_player.homecinema
        volume: 3
      - player: media_player.erker
        volume: 4
      - player: media_player.tafel
        volume: 3
      - player: media_player.keuken
        volume: 10
  - name: NPO Soul & Jazz
    media: NPO Soul & Jazz
    entities:
      - player: media_player.tv
        volume: 3
      - player: media_player.homecinema
        volume: 3
      - player: media_player.erker
        volume: 4
      - player: media_player.tafel
        volume: 3
      - player: media_player.keuken
        volume: 10
  - name: Radio 10
    media: Radio 10
    entities:
      - player: media_player.tv
        volume: 3
      - player: media_player.homecinema
        volume: 3
      - player: media_player.erker
        volume: 4
      - player: media_player.tafel
        volume: 3
      - player: media_player.keuken
        volume: 10
  - name: K-Joe Easy
    media: Joe Easy
    entities:
      - player: media_player.keuken
        volume: 10
  - name: K-Joe NL
    media: JOE Nederland
    entities:
      - player: media_player.keuken
        volume: 10
  - name: K-NPO Soul & Jazz
    media: NPO Soul & Jazz
    entities:
      - player: media_player.keuken
        volume: 14
  - name: K-Radio 10
    media: Radio 10
    entities:
      - player: media_player.keuken
        volume: 10
mediaArtworkOverrides:
  - ifMissing: false
    imageUrl: /local/images/sonoscard/tv1.gif
    mediaTitleEquals: TV
dynamicVolumeSlider: true
showVolumeUpAndDownButtons: true
mediaBrowserItemsPerRow: 5
``` 

![IMG_6048](https://github.com/punxaphil/custom-sonos-card/assets/71567372/2e4c12bc-e54e-4499-8185-9fa4797727c8)
