### ISSUE TITLE
mediaBrowserItemsAsList not working or is it me?

### ISSUE THREAD

**Issue by skavan** [punxaphil/custom-sonos-card#328]
**Checklist:**

- [ x] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**
v7.6.0
**Last working release (if known):**

**Browser and Operating System:**
Chrome. Windows 11

**Description of problem:**
The props `mediaTitle` and `mediaBrowserItemsAsList` don't seem to do anything. Might be me. Might be sonos-card!
```
type: vertical-stack
    cards:
      - type: custom:sonos-card
        layout:
          mediaItem:
            width: 15%
        sections:
          - volumes
          - groups
          - grouping
          - media browser
        mediaBrowserItemsAsList: true
```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
