### ISSUE TITLE
Remove media and controls background when artworkAsBackground: true

### ISSUE THREAD

**Issue by Vansmak** [punxaphil/custom-sonos-card#365]
**Is your feature request related to a problem? Please describe.**
When artworkAsBackground: true  there is a white background 

**Describe the solution you'd like**
the ability to make the whith background transparent

**Describe alternatives you've considered**
card_mod hasnt worked

**Additional context**

![2024-04-29 10_03_17-test – Home Assistant — Mozilla Firefox](https://github.com/punxaphil/custom-sonos-card/assets/16037573/3ac3b659-054c-4ccb-a0eb-fd6b252c7af7)
![2024-04-29 10_03_50-test – Home Assistant — Mozilla Firefox](https://github.com/punxaphil/custom-sonos-card/assets/16037573/2c61b323-8d93-442d-bd0d-e3f8f7a41d01)

**Comment by punxaphil** [comment]
```yaml
type: custom:sonos-card
artworkAsBackground: true
card_mod:
  style: |
    ha-card {
      --rgb-card-background-color: false;
    }
```
---
PunxaPhil
[![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/9bebc1f6-6bda-4cbd-b596-50d3d2f712de)](https://www.buymeacoffee.com/punxaphil)

**Comment by Vansmak** [comment]
Thank you, I tried so many/  Instead of false can i have my own semi-transparent background?
      --rgb-card-background-color: rgba(0, 0, 0, 0.5);  doesnt work
    }

**Comment by punxaphil** [comment]
```yaml
type: custom:sonos-card
artworkAsBackground: true
card_mod:
  style: 
    sonos-player$: |
      [background] {
        background-color: rgba(0,0,0, 0.3) !important;
      }
```
