### ISSUE TITLE
Multiple predefinedGroups with same speakers but different volume - doesn't set volume

### ISSUE THREAD

**Issue by finder39** [punxaphil/custom-sonos-card#369]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
v7.10.0

**Last working release (if known):**
I think pre-v7?

**Browser and Operating System:**
Chrome & iOS app

**Description of problem:**
I have multiple groups that have the same speakers in them: "All Loud", "All Medium", "All Quiet", & "All Subdued". The purpose of these is the have the same group but have quick buttons for volume level in the house. This works well as some speakers setup to my Ports should be set to a different volume than my actual Sonos speakers to actually play at the same level.

It used to be that I could tap one of those and even if they are all already grouped, it would properly set the volume to what I have in the `yaml`. Now it doesn't do that, it just leaves things in their current state.

Now I have added speakers to one room (all as Office) and I do seem to get more errors than before, as I do get errors such as in https://github.com/home-assistant/core/issues/82513. But that set is not included in these groups.

I do think there is an issue with the card that was introduced though which is why I've created this.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
My `predefinedGroups`:

```
        - name: All Loud
          volume: 37
          entities:
            - media_player.bathroom_sonos
            - media_player.bathroom_move_sonos
            - media_player.bedroom_sonos
            - media_player.dining_room_sonos
            - media_player.dining_room_move_sonos
            - player: media_player.family_room_sonos
              volume: 43
            - media_player.garage_entry_sonos
            - media_player.guest_bedroom_sonos
            - media_player.guest_office_sonos
            - media_player.kitchen_move_sonos
            - media_player.kitchen_sonos
            - player: media_player.media_loft_sonos
              volume: 43
        - name: All Medium
          volume: 25
          entities:
            - media_player.bathroom_sonos
            - media_player.bathroom_move_sonos
            - media_player.bedroom_sonos
            - media_player.dining_room_sonos
            - media_player.dining_room_move_sonos
            - player: media_player.family_room_sonos
              volume: 38
            - media_player.garage_entry_sonos
            - media_player.guest_bedroom_sonos
            - media_player.guest_office_sonos
            - media_player.kitchen_move_sonos
            - media_player.kitchen_sonos
            - player: media_player.media_loft_sonos
              volume: 38
        - name: All Quiet
          volume: 15
          entities:
            - media_player.bathroom_sonos
            - media_player.bathroom_move_sonos
            - media_player.bedroom_sonos
            - media_player.dining_room_sonos
            - media_player.dining_room_move_sonos
            - player: media_player.family_room_sonos
              volume: 30
            - media_player.garage_entry_sonos
            - media_player.guest_bedroom_sonos
            - media_player.guest_office_sonos
            - media_player.kitchen_move_sonos
            - media_player.kitchen_sonos
            - player: media_player.media_loft_sonos
              volume: 30
        - name: All Subdued
          # volume: 12
          volume: 10
          entities:
            - media_player.bathroom_sonos
            - media_player.bathroom_move_sonos
            - media_player.bedroom_sonos
            - media_player.dining_room_sonos
            - media_player.dining_room_move_sonos
            - player: media_player.family_room_sonos
              volume: 22
            - media_player.garage_entry_sonos
            - media_player.guest_bedroom_sonos
            - media_player.guest_office_sonos
            - media_player.kitchen_move_sonos
            - media_player.kitchen_sonos
            - player: media_player.media_loft_sonos
              volume: 22
```
