### ISSUE TITLE
Unable to group/join rooms either via tickbox or via predefined group

### ISSUE THREAD

**Issue by simkin** [punxaphil/custom-sonos-card#397]
**Checklist:**

- [ X ] I updated to the latest version available
- [ X ] I cleared the cache of my browser

**Release with the issue:**
V7.11.2

**Last working release (if known):**
couple of releases back, not sure how many

**Browser and Operating System:**
Windows 11
Firefox 127.0
Edge 125.0.2535.92 

**Description of problem:**

I am facing issues with my Sonos integration it seems. This issue occurred after my recent upgrade of HA core. I am wondering if this is a bug in HA, my config or else? Perhaps there is something I can do to assist with debugging of fix it myself?

The issue is reproducible when I use the sonon-card interface to add/join rooms via the room tickbox or the group button I prepared:
![afbeelding](https://github.com/punxaphil/custom-sonos-card/assets/958263/e1ca5666-854a-49c4-a27e-81c1130670fd)

The browser debug shows the following message:
![afbeelding](https://github.com/punxaphil/custom-sonos-card/assets/958263/455e4328-03b7-4342-8b96-30e8b8d787ed)

Please note that when I join/group the rooms via the Sonos app the volume slider IS working and the tick box is set. Volume control is also working now so I can control the device.
![afbeelding](https://github.com/punxaphil/custom-sonos-card/assets/958263/7d08dcf9-212d-4584-9d5b-c127e902a283)

When I search my HA log files for string Sonos I do find one entry:
```
Logger: homeassistant.components.sonos.speaker
Source: components/sonos/speaker.py:330
integration: Sonos (documentation, issues)
First occurred: 13 June 2024 at 15:51:47 (1 occurrences)
Last logged: 13 June 2024 at 15:51:47

Subscription renewal failed for Zithoek: Request timed out
```
Is that the rootcause of my problem? Any suggestion how to fix?

**Additional information:**
YAML
```
type: custom:sonos-card
sections:
  - player
  - volumes
  - groups
  - grouping
  - media browser
showVolumeUpAndDownButtons: true
dynamicVolumeSlider: false
title: SONOS
entityId: media_player.keuken
widthPercentage: 100
heightPercentage: 100
topFavorites:
  - ''
mediaBrowserShowTitleForThumbnailIcons: true
numberOfFavoritesToShow: 20
skipApplyButtonWhenGrouping: true
artworkAsBackground: false
predefinedGroups:
  - name: Keuken/Zithoek
    media: ''
    entities:
      - player: media_player.keuken
        volume: 20
      - player: media_player.zithoek
        volume: 20

```
