### ISSUE TITLE
Card not available

### ISSUE THREAD

**Issue by tamet83** [punxaphil/custom-sonos-card#51]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
Last one

**Last working release (if known):**
N/A

**Browser and Operating System:**
Hassio

**Description of problem:**
I followed the wiki steps without any result. The card doesn't show up as you can see from the screenshot

<img width="390" alt="Schermata 2022-03-13 alle 23 34 09" src="https://user-images.githubusercontent.com/7949570/158082049-ac821e71-ce2d-4f19-81dc-42ce74bde479.png">

Here the code inside my resources file:

```yaml
#Sonos Card
- url: /local/custom-sonos-card.js?v=1.0
  type: module
```

instead here is the minimum code required for the card:

```yaml
- type: custom:custom-sonos-card
  entities:
    - media_player.salotto
```

This is not the first custom component I use and I don't know why it doesn't work

**Additional information:**
