### ISSUE TITLE
Linking to specific player only work after crtl+F5

### ISSUE THREAD

**Issue by Nielsdewinter** [punxaphil/custom-sonos-card#527]
**Checklist:**

- I use custom-sonos-card v 7.21.3
- cleared the cache of my browser, yes that fix the problem, only i dont want to refresh my browser every time i want to link to specific sonos player

**Last working release (if known):**

**Browser and Operating System:**
Microsoft Edge
Version 130.0.2849.52 (Official build) (64-bit)

<!--
on a room page, i make a tap action on a mini-media-player, that navigate to my sonos page. I want link navigate to a specific sonos player

**code of room page**
type: custom:mini-media-player
entity: media_player.sonos_dining
tap_action:
  action: navigate
  navigation_path: /dashboard-home/Sonos#media_player.sonos_slaapkamer

**code of the sonos page**
type: custom:sonos-card
sections:
  - groups
  - grouping
  - volumes
  - player
  - media browser
title: sonos
showVolumeUpAndDownButtons: false
showFastForwardAndRewindButtons: false
hidePlayerControlPowerButton: false
hidePlayerControlShuffleButton: false
hidePlayerControlPrevTrackButton: false
hidePlayerControlNextTrackButton: false
entities:
  - media_player.sonos_slaapkamer
  - media_player.sonos_demi
  - media_player.sonos_gasten
  - media_player.sonos_dining
  - media_player.sonos_igor
  - media_player.sonos_study
  - media_player.sonos_tv
  - media_player.sonos_living
  - media_player.sauna

**Description of problem:**
The link redirect to the sonos page but not to the specific sonos player. After a CTRL+F5 the correct sonos player displayed.

can you have a look at this problem, thanks!
Niels

**Comment by Nielsdewinter** [comment]
Hi

I don’t have other cards on the pages that reproduce the issue. See screen shots. I use other cards on other pages. See list of hacs downloads.

Where can I find the cardconfig.

[image0.png][image1.png][image2.png]




Verstuurd vanaf mijn iPhone

Op 28 okt 2024 om 21:57 heeft Punxa Phil ***@***.***> het volgende geschreven:

﻿

I can't reproduce this. Do you have any other cards interfering with this behavior? Also, please share your cardconfig.

**Comment by punxaphil** [comment]
I see no screenshot

**Comment by Nielsdewinter** [comment]
Hi

Sorry don’t know what happened. Here the screenshots


[image0.png][image1.png][image2.png]
Verstuurd vanaf mijn iPhone

Op 29 okt 2024 om 07:12 heeft Punxa Phil ***@***.***> het volgende geschreven:

﻿

I see no screenshot

**Comment by punxaphil** [comment]
still nothing

**Comment by punxaphil** [comment]
Card config is the configuration of your card. Go into edit mode, edit your card, then go to code editor, copy the code and paste here.

**Comment by punxaphil** [comment]
It's working fine here, this is Edge:

https://github.com/user-attachments/assets/8ab43a11-8814-4e98-8681-f20e9eba9d01

**Comment by bdsoha** [comment]
You can test this by creating the dashboard and dummy `input_boolean` below.
When toggling the button, the pages change but are not referencing the current player chosen in the `groups` section.


### Dashboard

```yaml
views:
  - title: Home
    sections:
      - type: grid
        cards:
          - type: custom:sonos-card
            sections:
              - groups
        visibility:
          - condition: state
            entity: input_boolean.sonos_page
            state: 'on'
      - type: grid
        cards:
          - type: custom:sonos-card
            sections:
              - queue
        visibility:
          - condition: state
            entity: input_boolean.sonos_page
            state: 'off'
    badges:
      - type: entity
        show_name: false
        show_state: true
        show_icon: true
        entity: input_boolean.sonos_page
        tap_action:
          action: toggle
    type: sections
```
