### ISSUE TITLE
Volume Up and Down buttons don't work

### ISSUE THREAD

**Issue by Bram1nat0r** [punxaphil/custom-sonos-card#528]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
2024.10.4 / v7.21.0

**Last working release (if known):**
Unknown

**Browser and Operating System:**
Google Chrome Version 130.0.6723.70 / macOS 15.0.1 (24A348)

**Description of problem:**
Because I would like to have multiple SONOS cards in a SwipeCard configuration, the Volume slider doesn't work for me and therefor I set boolean :  `showVolumeUpAndDownButtons` to `True`.
The buttons do appear, but do not work.
I have tried multiple values of `volumeStepSize` but they don't have any effect.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
My card configuration:

```
type: custom:sonos-card
sections:
  - player
showVolumeUpAndDownButtons: true
showFastForwardAndRewindButtons: false
hidePlayerControlPowerButton: true
hidePlayerControlShuffleButton: true
showNonSonosPlayers: false
topFavorites:
  - ""
dynamicVolumeSlider: false
entities:
  - media_player.keuken
entityId: media_player.keuken
adjustVolumeRelativeToMainPlayer: false
hideVolumeCogwheel: true
title: SONOS Keuken
hidePlayerControlRepeatButton: true
playerVolumeEntityId: media_player.keuken
card_mod:
  style:
    sonos-player$ sonos-player-controls$: |
      sonos-volume {
        display: none;
      }
```

**Comment by punxaphil** [comment]
Does it work outside of swipecard?

**Comment by Bram1nat0r** [comment]
> Does it work outside of swipecard?

No, it doesn't.
I started off with the SONOS card in a regular View/Dashboard configuration.

**Comment by punxaphil** [comment]
1. What kind of player is it?
2. Does it work to adjust volume in standard builtin player?
3. Does it work in Developer Tools action? (see screenshot)
![image](https://github.com/user-attachments/assets/3177a28f-6da2-4cde-a2c0-b155bfc913d0)

4. Please share view of attributes (see screenshot)
![image](https://github.com/user-attachments/assets/8eb6cd14-b32e-46d8-86cc-a3ff05d73382)

**Comment by Bram1nat0r** [comment]
> 1. What kind of player is it?
SONOS Symfonisk

```
Table lamp: Eetkamer-Keuken
Serial Number: 54-2A-1B-54-59-42:B
Sonos OS: S2
Version: 16.4.2 (build 81.1-58074)
Hardware Version: 1.34.2.9-2.2
IP Address: 192.168.255.47
```

It also doesn't work on other player, such as a SONOS Connect

```
Connect: Kantoor
Serial Number: 94-9F-3E-BB-48-96:C
Sonos OS: S2
Version: 16.3.3 (build 80.1-56190)
Hardware Version: 1.22.1.5-2.1
IP Address: 192.168.255.49
```

> 2. Does it work to adjust volume in standard builtin player?
Yes, this works.

> 3. Does it work in Developer Tools action? (see screenshot)
Yes, this works :

```
action: media_player.volume_up
data: {}
target:
  entity_id: media_player.keuken
``` 

> 4. Please share view of attributes (see screenshot)

```
group_members:
  - null
volume_level: 0.09
is_volume_muted: false
media_content_id: >-
  x-sonos-spotify:spotify%3atrack%3a1xrSV0FyGg77IuJGYF3siH?sid=9&flags=8232&sn=26
media_content_type: music
media_duration: 401
media_position: 0
media_position_updated_at: "2024-10-29T06:59:11.960285+00:00"
media_title: At Night
media_artist: Shakedown
media_album_name: At Night
shuffle: true
repeat: "off"
queue_position: 1
queue_size: 50
device_class: speaker
entity_picture: >-
  /api/media_player_proxy/media_player.keuken?token=61807a07876253f08283f86b100dc28af8a327bca264de35ffb00736d283a7e3&cache=a6531a4487406df4
friendly_name: Keuken
supported_features: 4127295
```

```
source_list:
  - Line-in
group_members:
  - null
volume_level: 0.4
is_volume_muted: false
media_content_id: >-
  x-sonos-spotify:spotify%3atrack%3a0ilZMeXHPKDPjUc4Neu04f?sid=9&flags=8232&sn=26
media_content_type: music
media_duration: 416
media_position: 0
media_position_updated_at: "2024-10-29T09:20:29.107049+00:00"
media_title: Where Love Lives (Come On In) - Classic Mix
media_artist: Alison Limerick
media_album_name: Club Classics
shuffle: false
repeat: "off"
queue_position: 22
queue_size: 100
device_class: speaker
entity_picture: >-
  /api/media_player_proxy/media_player.kantoor?token=9ca2eea10207530db6214329a3dbc1c24ebadf7048994a2599ae02f2c2b5c9d0&cache=66bed7cd8b57d713
friendly_name: Kantoor
supported_features: 4127295

```

**Comment by punxaphil** [comment]
Everything looks good. Any errors in browser dev console?

**Comment by Bram1nat0r** [comment]
> Everything looks good. Any errors in browser dev console?

Tried in multiple browsers (desktop/mobile). No success.

No output in Dev Console (Desktop/Chrome browser)

**Comment by punxaphil** [comment]
Makes no sense to me. Please make a recording.

**Comment by Bram1nat0r** [comment]
> Makes no sense to me. Please make a recording.


https://github.com/user-attachments/assets/fc61525a-52a8-45da-9324-f51cc69c2970

**Comment by punxaphil** [comment]
Yeah, that doesn't look good.
Same if you simplify card config to the below?
```
title: SONOS_TEST
path: sonos-test
cards:
  - type: custom:sonos-card
    showVolumeUpAndDownButtons: true
```
