### ISSUE TITLE
specific player parameter only works after refresh

### ISSUE THREAD

**Issue by deluxestyle** [punxaphil/custom-sonos-card#605]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
8.6.0

**Last working release (if known):**
N/A

**Browser and Operating System:**
Edge, Chrome, Firefox, Safari, iOS App

**Description of problem:**

I have an overview dashboard with the sonos entities. from there I call the the action navigate with the url 

![Image](https://github.com/user-attachments/assets/35ada44e-7d94-4a4f-9970-102d162fcd94)

```
tap_action:
  action: navigate
  navigation_path: /lovelace/sonos#media_player.office

tap_action:
  action: navigate
  navigation_path: /lovelace/sonos#media_player.wohnzimmer
```
the dashboard sonos contains only the sonos card.

![Image](https://github.com/user-attachments/assets/1c6282e9-a7fe-4e68-83bb-36553b0fd921)

Unfortunately the url parameter is only taken into account when I refresh the view.
When I click on the one of the entities it opens the sonos dashboard always with the last open player. not with that from the parameter.

**Javascript errors shown in the web inspector (if applicable):**

none

**Additional information:**
